"use strict";
exports.__esModule = true;
var test_1 = require("./test");
var c = new test_1.LRUCache(test_1.LRUCache.WithMax(3), test_1.LRUCache.WithMaxAge(1000));
c.set("k1", "v1");
c.set("k2", "v2");
console.log(c.get("k1"));
c.set("k3", "v3");
c.set("k4", "v4");
console.log(c.get("k1"));
console.log(c.get("k2"));
console.log(c.get("k3"));
console.log(c.get("k4"));
